-- local cmp = require("cmp")
-- cmp.setup {
--     mapping = {
--         ['<M-;>'] = cmp.mapping(function(fallback)
--           vim.api.nvim_feedkeys(vim.fn['copilot#Accept'](vim.api.nvim_replace_termcodes('<Tab>', true, true, true)), 'n',
--               true)
--         end)
--     },
-- }
